[package]
name = "threadpool_rs"
version = "0.1.0"
edition = "2021"


[features]
default = []
log = ["dep:log"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { version = "0.4.20", optional = true }
